//! Build script: bakes OAuth credentials into the binary at compile time.
//!
//! Reads `COLAB_EXTENSION_CLIENT_ID` and `COLAB_EXTENSION_CLIENT_NOT_SO_SECRET`
//! from the build environment and generates `$OUT_DIR/embedded_secrets.rs`
//! containing `embedded_client_id()` / `embedded_client_secret()` helpers.
//!
//! The literal values are wrapped in `obfstr::obfstr!(…)`, which XOR-encodes
//! them with a compile-time randomized key. As a result the plaintext does
//! NOT appear in the final `.rodata` section and is invisible to `strings`,
//! casual reverse engineering, and automated secret scanners.
//!
//! This is obfuscation, not encryption — a determined attacker running the
//! binary under a debugger can still recover the values at runtime. The goal
//! is to raise the cost above trivial extraction, not to achieve secrecy.
//!
//! When either env var is empty (e.g. a plain local `cargo build`), the
//! generated helpers return empty strings and `config.rs` transparently
//! falls back to the usual runtime env-var / `config.toml` lookup.

use std::env;
use std::fs;
use std::path::PathBuf;

const CLIENT_ID_VAR: &str = "COLAB_EXTENSION_CLIENT_ID";
const CLIENT_SECRET_VAR: &str = "COLAB_EXTENSION_CLIENT_NOT_SO_SECRET";

fn main() {
    // Re-run this build script whenever the script itself or either of the
    // build-time secrets changes value. `rerun-if-env-changed` teaches cargo
    // to track the env var as part of the crate's fingerprint, so switching
    // between "unset" (dev) and "set" (release CI) correctly triggers a rebuild.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed={CLIENT_ID_VAR}");
    println!("cargo:rerun-if-env-changed={CLIENT_SECRET_VAR}");

    let client_id = env::var(CLIENT_ID_VAR).unwrap_or_default();
    let client_secret = env::var(CLIENT_SECRET_VAR).unwrap_or_default();

    // Warn loudly if the build is half-configured — almost always a CI mistake.
    if client_id.is_empty() ^ client_secret.is_empty() {
        println!(
            "cargo:warning=colab-cli: only one of {CLIENT_ID_VAR} / {CLIENT_SECRET_VAR} is set at build time; both or neither is expected"
        );
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set by cargo"));
    let dest = out_dir.join("embedded_secrets.rs");

    // `{:?}` (Debug) produces a valid, properly-escaped Rust string literal
    // for any input, so we don't have to hand-roll escaping for backslashes,
    // quotes, or control characters.
    let client_id_lit = format!("{client_id:?}");
    let client_secret_lit = format!("{client_secret:?}");

    let generated = format!(
        r##"// @generated by build.rs — DO NOT EDIT.
//
// OAuth credentials baked in at compile time. The literal values are fed to
// `obfstr::obfstr!`, which emits XOR-obfuscated bytes + a per-build random
// key. The plaintext never appears in .rodata and is invisible to `strings`.

#[inline]
pub fn embedded_client_id() -> String {{
    obfstr::obfstr!({client_id_lit}).to_string()
}}

#[inline]
pub fn embedded_client_secret() -> String {{
    obfstr::obfstr!({client_secret_lit}).to_string()
}}
"##
    );

    fs::write(&dest, generated).expect("failed to write embedded_secrets.rs");
}
